<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Related search terms_product-image-photo</name>
   <tag></tag>
   <elementGuidId>9d57a3d8-edeb-4ab7-83d8-01ab211e9ba8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[3]/div/div[2]/div[2]/ol/li/div/a/span/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.product-image-photo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d369df27-f512-47d8-b00f-763f3f9e00ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image-photo</value>
      <webElementGuid>766c2d57-a816-468a-94f0-c7cfd0e76fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/7c4c1ed835fbbf2269f24539582c6d44/w/h/wh05-white_main_1.jpg</value>
      <webElementGuid>0653eafe-ee76-4526-8e27-41aaa3977801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>b95050f1-8912-4bc2-8f71-acf5ffe723df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>40fca419-58a2-4dc8-b76d-c99f9bbb518c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Selene Yoga Hoodie</value>
      <webElementGuid>414cfef3-81bf-403b-8a57-0b0f27a12042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;search results&quot;]/div[@class=&quot;products wrapper grid products-grid&quot;]/ol[@class=&quot;products list items product-items&quot;]/li[@class=&quot;item product product-item&quot;]/div[@class=&quot;product-item-info&quot;]/a[@class=&quot;product photo product-item-photo&quot;]/span[@class=&quot;product-image-container&quot;]/span[@class=&quot;product-image-wrapper&quot;]/img[@class=&quot;product-image-photo&quot;]</value>
      <webElementGuid>d758b644-9a18-4f4f-8b8a-afc6c0f3d081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[3]/div/div[2]/div[2]/ol/li/div/a/span/span/img</value>
      <webElementGuid>e68ecd03-b393-4e16-a387-20d746101bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Selene Yoga Hoodie']</value>
      <webElementGuid>1b0027db-51b5-49b3-afc2-acbb948f1aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>cde4369f-5662-46af-bc35-84b28c8db79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/7c4c1ed835fbbf2269f24539582c6d44/w/h/wh05-white_main_1.jpg' and @alt = 'Selene Yoga Hoodie']</value>
      <webElementGuid>8fc6b72a-ccab-4309-9341-ae6064a6c200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
