<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Subtotal_product-image-photo</name>
   <tag></tag>
   <elementGuidId>95c5dbe8-8ebc-408c-a5e0-a8263d757fca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.col.item > a.product-item-photo > span.product-image-container > span.product-image-wrapper > img.product-image-photo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='shopping-cart-table']/tbody/tr/td/a/span/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=table[name=&quot;Shopping Cart Items&quot;i] >> internal:attr=[title=&quot;Olivia 1/4 Zip Light Jacket&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c7a6b2e2-82cc-4172-bba4-018f635d3446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image-photo</value>
      <webElementGuid>9cfe8102-27f1-4fec-ae2e-37c8ba6b8c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/b45fda5d42e04db84d57ecfd089c603c/w/j/wj12-blue_main_1.jpg</value>
      <webElementGuid>ba85b949-fe67-4882-930f-e15216f39780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-width</name>
      <type>Main</type>
      <value>165</value>
      <webElementGuid>2a9d9532-8685-46aa-958b-0fbcc0425250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-height</name>
      <type>Main</type>
      <value>165</value>
      <webElementGuid>824746b0-b655-40a7-8863-c5e481da23cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Olivia 1/4 Zip Light Jacket</value>
      <webElementGuid>73831d86-ee93-4550-9ede-1c0621e71d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopping-cart-table&quot;)/tbody[@class=&quot;cart item&quot;]/tr[@class=&quot;item-info&quot;]/td[@class=&quot;col item&quot;]/a[@class=&quot;product-item-photo&quot;]/span[@class=&quot;product-image-container&quot;]/span[@class=&quot;product-image-wrapper&quot;]/img[@class=&quot;product-image-photo&quot;]</value>
      <webElementGuid>97024dfc-970d-40dc-a2f7-b30cb91a1e5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='shopping-cart-table']/tbody/tr/td/a/span/span/img</value>
      <webElementGuid>4340234b-4618-4968-8da2-9343f985439b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Olivia 1/4 Zip Light Jacket'])[2]</value>
      <webElementGuid>dd7d5ae6-b2f6-4d70-a772-752a55c7a748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a/span/span/img</value>
      <webElementGuid>40f18b20-d468-4caf-9702-55a26b9a9a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/b45fda5d42e04db84d57ecfd089c603c/w/j/wj12-blue_main_1.jpg' and @alt = 'Olivia 1/4 Zip Light Jacket']</value>
      <webElementGuid>4c674963-5855-46b6-a9e2-402b45f613f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
