<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_28.00_product-image-photo</name>
   <tag></tag>
   <elementGuidId>8194d5d6-90e8-47e0-95e1-b0e0259410c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[5]/div[2]/div/ol/li[10]/div/a/span/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8f5ffd32-a536-4a09-8dfa-3bf5a28cd31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image-photo</value>
      <webElementGuid>3095a0d8-49fe-445e-9f28-140a74d66562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/c6a30ab320476737d4efb24ff49cc5f5/w/s/ws10-red_main_1.jpg</value>
      <webElementGuid>cf44daf9-3d26-4bb7-a7bb-3048f401599c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-width</name>
      <type>Main</type>
      <value>152</value>
      <webElementGuid>5a61a453-954c-4f8e-bc81-da3d50016b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-height</name>
      <type>Main</type>
      <value>190</value>
      <webElementGuid>f1966206-80ff-4a02-b02b-8babd53e7184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Karissa V-Neck Tee</value>
      <webElementGuid>0c55e664-5b29-4434-a240-56f824315fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;block upsell&quot;]/div[@class=&quot;block-content content&quot;]/div[@class=&quot;products wrapper grid products-grid products-upsell&quot;]/ol[@class=&quot;products list items product-items&quot;]/li[@class=&quot;item product product-item&quot;]/div[@class=&quot;product-item-info&quot;]/a[@class=&quot;product photo product-item-photo&quot;]/span[@class=&quot;product-image-container&quot;]/span[@class=&quot;product-image-wrapper&quot;]/img[@class=&quot;product-image-photo&quot;]</value>
      <webElementGuid>0f6af989-dd1a-4356-b1b8-42e155f5c851</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[5]/div[2]/div/ol/li[10]/div/a/span/span/img</value>
      <webElementGuid>b8a1c09f-ba66-423f-befa-e8456c0d8be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Karissa V-Neck Tee']</value>
      <webElementGuid>b0003d43-a79a-4a6e-8c93-d5ed0f200564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/div/a/span/span/img</value>
      <webElementGuid>8618e1cc-a5a6-4b17-af48-13724e9c1e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/c6a30ab320476737d4efb24ff49cc5f5/w/s/ws10-red_main_1.jpg' and @alt = 'Karissa V-Neck Tee']</value>
      <webElementGuid>6504ca4e-5592-4093-a2b5-f37656bbd7e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
