<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_M</name>
   <tag></tag>
   <elementGuidId>f64dcf35-8ec3-48dd-afae-563227b5a6c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option-label-size-143-item-168</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='option-label-size-143-item-168']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;M&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aaffab20-1449-45b6-98be-67edc9f8f25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-option text</value>
      <webElementGuid>ecd05903-5272-42cd-896b-ff6f12e2ffcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-label-size-143-item-168</value>
      <webElementGuid>fcc288aa-1417-4a25-b5c3-444febb0f08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>33dc7c2c-e9e0-4f19-8df2-c60feafb32c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>43c63b10-cc30-4f7f-b7f6-f37dfb447757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>option-label-size-143</value>
      <webElementGuid>5353c19f-b408-46dc-9099-ad643a0ceaa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f1ee2bbb-ac4c-49ed-828b-352b285a3a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>70ac7026-aa57-43fb-b2b4-f02ed3145eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-id</name>
      <type>Main</type>
      <value>168</value>
      <webElementGuid>74cce369-8ad1-4e18-8b21-c3cf1e7e08b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-label</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>4d36992c-7efa-465d-8e65-d87b379dbc1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>0740d2f5-5277-4563-9d87-d8bb4bfc4b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-tooltip-value</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>69c36e91-5a9f-4269-a83d-7b52e62b827a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>60f1dacc-08b4-4b7d-b489-8881310e7062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thumb-width</name>
      <type>Main</type>
      <value>110</value>
      <webElementGuid>b02e7300-fe05-4c1d-9737-d69b3ab63400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thumb-height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>204f3e88-9367-47d6-b606-e2b76188a467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>d35bec6c-ef2b-49a2-bd7d-b43cc4253a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option-label-size-143-item-168&quot;)</value>
      <webElementGuid>aad92248-6bce-4e40-9ba7-11a810aeed4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='option-label-size-143-item-168']</value>
      <webElementGuid>fdd61ddf-560a-4674-a0c2-73862a693f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-options-wrapper']/div/div/div/div/div[3]</value>
      <webElementGuid>b6986ece-0e9c-40a3-bf0e-962cc9b78042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::div[1]</value>
      <webElementGuid>a77671cd-3b82-47a5-ad7a-05bf3d3d7928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XS'])[1]/following::div[2]</value>
      <webElementGuid>bb2da005-8cdf-44d8-a755-e6c8f141016e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='L'])[1]/preceding::div[1]</value>
      <webElementGuid>ec462008-7174-4c79-b997-306c4c463253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XL'])[1]/preceding::div[2]</value>
      <webElementGuid>fd4fc312-50e6-42dc-b087-6828929570bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='M']/parent::*</value>
      <webElementGuid>b79bc69b-8603-440e-857d-fa10f3bb4a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div[3]</value>
      <webElementGuid>a2f86944-3057-437b-bbaa-e985167fd653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'option-label-size-143-item-168' and (text() = 'M' or . = 'M')]</value>
      <webElementGuid>86212f2a-04bc-4733-8a75-5a24a2dbf1bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
