<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Forgot Your Password_fotorama__arr__arr</name>
   <tag></tag>
   <elementGuidId>bc3c1f66-cc9a-4c57-9233-2fd19c08c49b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fotorama__arr__arr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[5]/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Previous&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b4daefa1-6696-4257-a2dd-da79e5ff0e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fotorama__arr__arr</value>
      <webElementGuid>62561c62-2b63-4129-a42d-9c4f3ac51644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fotorama__fullscreen&quot;]/body[@class=&quot;page-product-configurable catalog-product-view product-olivia-1-4-zip-light-jacket categorypath-women-tops-women-jackets-women category-jackets-women page-layout-1column fotorama__fullscreen&quot;]/div[@class=&quot;fotorama-item fotorama fotorama1743683924913 fotorama--fullscreen&quot;]/div[@class=&quot;fotorama__wrap fotorama__wrap--css3 fotorama__wrap--slide fotorama__wrap--toggle-arrows&quot;]/div[@class=&quot;fotorama__stage&quot;]/div[@class=&quot;fotorama__arr fotorama__arr--prev&quot;]/div[@class=&quot;fotorama__arr__arr&quot;]</value>
      <webElementGuid>5ad0231f-730d-4ece-a6d5-9461f6cae153</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div[2]/div</value>
      <webElementGuid>b6cf4631-47a4-47bc-8b8b-f50b3bc7a84d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
