<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_purple</name>
   <tag></tag>
   <elementGuidId>bb1d2da4-18d4-402b-88ab-fd91e9b8b951</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.fotorama__img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[3]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.fotorama__img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2099bde5-0249-4a6e-816b-97abd807bb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/d34482110da20c5e24f97c38fb219fb3/w/j/wj12-purple_main_1.jpg</value>
      <webElementGuid>b2d283e6-45ec-4da0-bf2e-ec43e34f4a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fotorama__img</value>
      <webElementGuid>1cda934b-b9bd-4bbe-9527-3f8b5d3b1e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b1832fda-e509-46a0-a71a-a86070047ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;product media&quot;]/div[@class=&quot;gallery-placeholder&quot;]/div[@class=&quot;fotorama-item fotorama fotorama1743684185150&quot;]/div[@class=&quot;fotorama__wrap fotorama__wrap--css3 fotorama__wrap--slide fotorama__wrap--toggle-arrows&quot;]/div[@class=&quot;fotorama__stage&quot;]/div[@class=&quot;fotorama__stage__shaft fotorama__grab&quot;]/div[@class=&quot;fotorama__stage__frame magnify-wheel-loaded fotorama_vertical_ratio fotorama__loaded fotorama__loaded--img fotorama__active&quot;]/img[@class=&quot;fotorama__img&quot;]</value>
      <webElementGuid>10ddfa66-36fc-452f-bc95-41190735df97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[3]/div/img</value>
      <webElementGuid>b74bdbd5-7e8d-415a-a3e7-365ff68d397f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/d34482110da20c5e24f97c38fb219fb3/w/j/wj12-purple_main_1.jpg')]</value>
      <webElementGuid>eea89dc1-465b-4645-a2c0-97552e1a5ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>3e2a6bf3-21d8-416d-8652-888e5c58b6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/d34482110da20c5e24f97c38fb219fb3/w/j/wj12-purple_main_1.jpg']</value>
      <webElementGuid>baaa0e00-ded2-4265-9e0a-a207bd456db7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
