<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mg_black_zoom</name>
   <tag></tag>
   <elementGuidId>deeaf770-07da-43ed-b9fb-66c9c975ab27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.fotorama__img--full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/c2e58f207611755436220741b3fe027b/w/j/wj12-black_main_1.jpg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.fotorama__img--full >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>23fd702c-33da-4079-b378-e3463c419000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/c2e58f207611755436220741b3fe027b/w/j/wj12-black_main_1.jpg</value>
      <webElementGuid>8538ac7e-13ba-48dd-a9fc-7d27bcfc189f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fotorama__img--full</value>
      <webElementGuid>beecf5b5-a2ee-4114-8a89-45d5f7bf8c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f3feeeee-4d6f-4ec3-9402-8587ae90e331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fotorama__fullscreen&quot;]/body[@class=&quot;page-product-configurable catalog-product-view product-olivia-1-4-zip-light-jacket categorypath-women-tops-women-jackets-women category-jackets-women page-layout-1column fotorama__fullscreen&quot;]/div[@class=&quot;fotorama-item fotorama fotorama1743683877253 fotorama--fullscreen&quot;]/div[@class=&quot;fotorama__wrap fotorama__wrap--css3 fotorama__wrap--slide fotorama__wrap--toggle-arrows&quot;]/div[@class=&quot;fotorama__stage&quot;]/div[@class=&quot;fotorama__stage__shaft fotorama__grab&quot;]/div[@class=&quot;fotorama__stage__frame magnify-wheel-loaded fotorama_vertical_ratio fotorama__loaded fotorama__loaded--img fotorama__active fotorama__loaded--full&quot;]/img[@class=&quot;fotorama__img--full&quot;]</value>
      <webElementGuid>1663e4e3-e569-472f-93c1-1b599df84727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/c2e58f207611755436220741b3fe027b/w/j/wj12-black_main_1.jpg')]</value>
      <webElementGuid>ee0293ca-ae17-4a18-ba34-2fda0c6a8d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>f1961e3b-e4c4-44e8-bf0a-0b410c88500e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/c2e58f207611755436220741b3fe027b/w/j/wj12-black_main_1.jpg']</value>
      <webElementGuid>8a7e9e4a-8baf-4194-abd9-78bb9bebcb09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
