<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zoom-out</name>
   <tag></tag>
   <elementGuidId>c3c535c4-fdda-48e4-9a96-d40003764f5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fotorama__zoom-out.zoom-out-loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Zoom out&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5120302-1f9d-4d1b-b636-df593c0fa43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fotorama__zoom-out zoom-out-loaded</value>
      <webElementGuid>cd9a48df-0471-4453-b276-36e1c41b714b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gallery-role</name>
      <type>Main</type>
      <value>fotorama__zoom-out</value>
      <webElementGuid>e5c52e0e-d517-49f0-a835-dc59b5a8bc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Zoom out</value>
      <webElementGuid>0c18da73-d13f-4a82-9f17-29715bd71d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>69e458ba-5432-40b0-9a8e-d9b34b64973a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c7e4fe9a-4f61-4c98-84ea-4220c7d42b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fotorama__fullscreen&quot;]/body[@class=&quot;page-product-configurable catalog-product-view product-olivia-1-4-zip-light-jacket categorypath-women-tops-women-jackets-women category-jackets-women page-layout-1column fotorama__fullscreen&quot;]/div[@class=&quot;fotorama-item fotorama fotorama1743683924913 fotorama--fullscreen&quot;]/div[@class=&quot;fotorama__wrap fotorama__wrap--css3 fotorama__wrap--slide fotorama__wrap--toggle-arrows&quot;]/div[@class=&quot;fotorama__stage&quot;]/div[@class=&quot;fotorama__zoom-out zoom-out-loaded&quot;]</value>
      <webElementGuid>713a1c5b-f296-432d-b779-f08d19b8d213</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]</value>
      <webElementGuid>0f37f826-e836-4614-b750-e9969ebffa41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
