<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_29.00_product-image-photo</name>
   <tag></tag>
   <elementGuidId>74c98e49-a5f2-47c9-a3ff-9bd2ea030733</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[5]/div[2]/div/ol/li[3]/div/a/span/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>deb82f7f-87c4-4572-a660-c4062ea6827e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image-photo</value>
      <webElementGuid>725d0864-4b8e-40d0-ab5b-f16b18b758d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/c6a30ab320476737d4efb24ff49cc5f5/w/s/ws06-purple_main_2.jpg</value>
      <webElementGuid>388ee135-cef3-47cb-ac7b-be37d3cf9240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-width</name>
      <type>Main</type>
      <value>152</value>
      <webElementGuid>1e9de9f3-ac97-44e9-8195-5594e5a310c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-height</name>
      <type>Main</type>
      <value>190</value>
      <webElementGuid>ead75446-1f58-45bf-b0dc-ce3dd3184b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Elisa EverCool™ Tee</value>
      <webElementGuid>22c7c7e2-da5b-46b7-a852-02051b29c637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;block upsell&quot;]/div[@class=&quot;block-content content&quot;]/div[@class=&quot;products wrapper grid products-grid products-upsell&quot;]/ol[@class=&quot;products list items product-items&quot;]/li[@class=&quot;item product product-item&quot;]/div[@class=&quot;product-item-info&quot;]/a[@class=&quot;product photo product-item-photo&quot;]/span[@class=&quot;product-image-container&quot;]/span[@class=&quot;product-image-wrapper&quot;]/img[@class=&quot;product-image-photo&quot;]</value>
      <webElementGuid>4d5cf31b-0691-4b88-afd0-e40b7f8fd3c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[5]/div[2]/div/ol/li[3]/div/a/span/span/img</value>
      <webElementGuid>097235f8-ddc5-4888-b280-093318d297b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Elisa EverCool™ Tee']</value>
      <webElementGuid>33fb4018-e5a6-42f5-87b9-1e76389c743b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/a/span/span/img</value>
      <webElementGuid>f33b6770-cba0-43c2-8a1c-d3afbf1712ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/c6a30ab320476737d4efb24ff49cc5f5/w/s/ws06-purple_main_2.jpg' and @alt = 'Elisa EverCool™ Tee']</value>
      <webElementGuid>fe464637-49b6-4048-9b2a-d784fdce3329</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
