<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Related Products_product-image-photo</name>
   <tag></tag>
   <elementGuidId>0a7350ac-126d-45be-b51a-1c42807abce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[5]/div[2]/div/ol/li/div/a/span/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.product.photo.product-item-photo > span.product-image-container > span.product-image-wrapper > img.product-image-photo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>97ed046c-a0ee-4109-ac8d-b0f0f4abb758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image-photo</value>
      <webElementGuid>e9a43a97-c721-4212-bba6-3ecbd5f1113c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/c6a30ab320476737d4efb24ff49cc5f5/w/s/ws11-yellow_main_1.jpg</value>
      <webElementGuid>7dd8b471-c904-4706-b1a9-864317521ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-width</name>
      <type>Main</type>
      <value>152</value>
      <webElementGuid>ab6fa4ed-558a-4492-9b88-80af7b340ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-height</name>
      <type>Main</type>
      <value>190</value>
      <webElementGuid>9e5c26f7-c017-424a-b39c-d8f705d3cad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Diva Gym Tee</value>
      <webElementGuid>08d9e153-ae5b-4099-9530-6a14327e021b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;block related&quot;]/div[@class=&quot;block-content content&quot;]/div[@class=&quot;products wrapper grid products-grid products-related&quot;]/ol[@class=&quot;products list items product-items&quot;]/li[@class=&quot;item product product-item&quot;]/div[@class=&quot;product-item-info&quot;]/a[@class=&quot;product photo product-item-photo&quot;]/span[@class=&quot;product-image-container&quot;]/span[@class=&quot;product-image-wrapper&quot;]/img[@class=&quot;product-image-photo&quot;]</value>
      <webElementGuid>cea16d72-d3b2-4413-9305-7a1ac075a52e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[5]/div[2]/div/ol/li/div/a/span/span/img</value>
      <webElementGuid>78aa4207-aca7-4e06-9a3f-605057019bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Diva Gym Tee']</value>
      <webElementGuid>df4fc653-8eae-48c5-b933-d3356c04fa72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/ol/li/div/a/span/span/img</value>
      <webElementGuid>cbdb9243-807b-4435-994b-fd78bedc89f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/c6a30ab320476737d4efb24ff49cc5f5/w/s/ws11-yellow_main_1.jpg' and @alt = 'Diva Gym Tee']</value>
      <webElementGuid>5e6dbf24-eb3c-4cdc-87ee-74946973f031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
