<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Color_swatch-option color</name>
   <tag></tag>
   <elementGuidId>79e8e438-30ce-410b-abcc-5106edc6b566</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='narrow-by-list']/div[4]/div[2]/div/div/a[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Blue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>baac7993-dbd6-486c-9135-e43b52d7e0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-option color </value>
      <webElementGuid>0f366da0-97e0-4fca-a389-aaf659767065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>453d3f02-dbfd-4910-b7a8-321708405edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a64e8bd8-75c2-4ade-8a03-1cd799ce929b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-id</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>8a4a57b5-7e53-45f5-b918-257b7fb67875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-label</name>
      <type>Main</type>
      <value>Blue</value>
      <webElementGuid>643a6f2f-f9b7-4709-9af2-5a4839e5609d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-tooltip-value</name>
      <type>Main</type>
      <value>#1857f7</value>
      <webElementGuid>19a657c8-4666-4422-9559-646430ffb951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;narrow-by-list&quot;)/div[@class=&quot;filter-options-item allow active&quot;]/div[@class=&quot;filter-options-content&quot;]/div[@class=&quot;swatch-attribute swatch-layered color&quot;]/div[@class=&quot;swatch-attribute-options clearfix&quot;]/a[@class=&quot;swatch-option-link-layered&quot;]/div[@class=&quot;swatch-option color&quot;]</value>
      <webElementGuid>e1126904-5b91-43c7-9737-b92287bdf865</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='narrow-by-list']/div[4]/div[2]/div/div/a[2]/div</value>
      <webElementGuid>27245c53-69e2-45be-84ef-9d1ac41c430b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/a[2]/div</value>
      <webElementGuid>fd9c4332-8172-434b-a904-c3b1180b9f55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
