<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Set Descending Direction_product-image-photo_1</name>
   <tag></tag>
   <elementGuidId>8c2f0809-8c1b-4f7c-b570-26c7a5a7a483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.product-image-photo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[3]/div/div[3]/ol/li/div/a/span/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Jade Yoga Jacket-XS-Blue&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>36b81375-97f3-4863-8341-57fab0a1be20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image-photo</value>
      <webElementGuid>2e53bbd6-f08c-4c75-8354-602c93fba84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/7c4c1ed835fbbf2269f24539582c6d44/w/j/wj09-blue_main_1.jpg</value>
      <webElementGuid>70515a74-0b1d-4557-baa0-c0fe79656f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>ae6eb8c7-cb97-44a2-86c7-1cf2eab2964f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>d5e3968c-e854-4aad-a6e3-fb5b61015b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Jade Yoga Jacket-XS-Blue</value>
      <webElementGuid>d8e60b6b-3752-41a5-8cea-f99a7a011158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;products wrapper grid products-grid&quot;]/ol[@class=&quot;products list items product-items&quot;]/li[@class=&quot;item product product-item&quot;]/div[@class=&quot;product-item-info&quot;]/a[@class=&quot;product photo product-item-photo&quot;]/span[@class=&quot;product-image-container&quot;]/span[@class=&quot;product-image-wrapper&quot;]/img[@class=&quot;product-image-photo&quot;]</value>
      <webElementGuid>efd54a30-f19c-4d0b-b474-c01eac9b01ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[3]/div/div[3]/ol/li/div/a/span/span/img</value>
      <webElementGuid>2806a50c-4c77-444d-b1d1-ccba3a70667a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Jade Yoga Jacket-XS-Blue']</value>
      <webElementGuid>69cd227d-6635-44b6-9514-784b3efbc6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>22f84b71-de9f-44bc-85ff-8e3b1d9bf7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://magento.softwaretestingboard.com/pub/media/catalog/product/cache/7c4c1ed835fbbf2269f24539582c6d44/w/j/wj09-blue_main_1.jpg' and @alt = 'Jade Yoga Jacket-XS-Blue']</value>
      <webElementGuid>2d637df9-b1f3-4163-b195-809d3a4fa739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
